// <auto-generated />
using System;
using EduInfoPortalBlazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EduInfoPortalBlazor.Migrations
{
    [DbContext(typeof(StorageService))]
    [Migration("20210217083817_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("EduInfoPortalBlazor.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetMinScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPaidPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaidMinScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaidPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profile")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Specialty");
                });

            modelBuilder.Entity("ExamSpecialty", b =>
                {
                    b.Property<int>("ExamsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialtiesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExamsId", "SpecialtiesId");

                    b.HasIndex("SpecialtiesId");

                    b.ToTable("ExamSpecialty");
                });

            modelBuilder.Entity("ProfessionSpecialty", b =>
                {
                    b.Property<int>("ProfessionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialtiesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfessionsId", "SpecialtiesId");

                    b.HasIndex("SpecialtiesId");

                    b.ToTable("ProfessionSpecialty");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Faculty", b =>
                {
                    b.HasOne("EduInfoPortalBlazor.Models.Institution", "Institution")
                        .WithMany("Faculties")
                        .HasForeignKey("InstitutionId");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Institution", b =>
                {
                    b.HasOne("EduInfoPortalBlazor.Models.City", "City")
                        .WithMany("Institutions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Specialty", b =>
                {
                    b.HasOne("EduInfoPortalBlazor.Models.Faculty", "Faculty")
                        .WithMany("Specialties")
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("ExamSpecialty", b =>
                {
                    b.HasOne("EduInfoPortalBlazor.Models.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduInfoPortalBlazor.Models.Specialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfessionSpecialty", b =>
                {
                    b.HasOne("EduInfoPortalBlazor.Models.Profession", null)
                        .WithMany()
                        .HasForeignKey("ProfessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduInfoPortalBlazor.Models.Specialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.City", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Faculty", b =>
                {
                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("EduInfoPortalBlazor.Models.Institution", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
